package designPattern.bigDataTinyurl;

/*
 *  Approach : 
 *  
 *  https://github.com/delight-im/ShortURL/blob/master/Microsoft%20SQL%20Server/ShortURL.sql
 */
class URLShortener {
	public static final String BASE_STRING = "9a8b7c6A5B4C3D2E1F0GdHeIfJgKhLijMkNlOmPnQoRpSqTrUsVtWuXvYwZx-y_z";
	public static final int BASE_LENGTH = BASE_STRING.length();
	
	public static void main(String []args) {
		URLShortener urlShort = new URLShortener();
		String encodedString = urlShort.encode(123456789);
		System.out.println(encodedString);
		System.out.println(urlShort.decode(encodedString));
	}
	
	public static String encode(int autogeneratedId) {
		StringBuffer st = new StringBuffer();
		while(autogeneratedId > 0) {
			st.append(BASE_STRING.charAt(autogeneratedId % BASE_LENGTH));
			autogeneratedId = autogeneratedId / BASE_LENGTH;
		}
		
		return st.toString();
	}
	
	public static int decode(String encodedString) {
		int autogeneratedId = 0;
		for(int index=0; index<encodedString.length(); index++) {
			autogeneratedId = (autogeneratedId * BASE_LENGTH ) +  BASE_STRING.indexOf(encodedString.charAt(index));
		}
		return autogeneratedId;
	}
}
